FROM python:3.10

RUN mkdir flask-website/
WORKDIR /flask-website/

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY app/ app/
COPY migrations/ migrations/
COPY flask_website.py config.py docker/flask/entrypoint_flask.sh ./
RUN chmod a+x entrypoint_flask.sh

EXPOSE 8008
ENTRYPOINT ["./entrypoint_flask.sh"]
