"""use self referential for blogpage unpublished

Revision ID: 0498bb0f1d52
Revises: d4b2eff3dfb3
Create Date: 2024-09-30 00:49:49.954315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0498bb0f1d52'
down_revision = 'd4b2eff3dfb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publishing_sibling_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'blogpage', ['publishing_sibling_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('publishing_sibling_id')

    # ### end Alembic commands ###
