"""rename html_color_class

Revision ID: 2618b71f1f4a
Revises: c1ac6b60fab0
Create Date: 2024-09-29 23:09:26.096366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2618b71f1f4a'
down_revision = 'c1ac6b60fab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.alter_column(column_name='html_color_class', new_column_name='color', existing_type=sa.String(length=100))
        batch_op.alter_column('published',
               existing_type=mysql.TINYINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.alter_column(column_name='color', new_column_name='html_color_class', existing_type=sa.String(length=100))
        batch_op.alter_column('published',
               existing_type=mysql.TINYINT(),
               nullable=True)

    # ### end Alembic commands ###
