"""collation charset test

Revision ID: 35a55c3553be
Revises: a48f9d6f41da
Create Date: 2024-07-29 09:53:01.067029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35a55c3553be'
down_revision = 'a48f9d6f41da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb3_bin'),
               type_=sa.UnicodeText(length=100000, collation='utf8mb4_bin'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.UnicodeText(length=100000, collation='utf8mb4_bin'),
               type_=mysql.MEDIUMTEXT(collation='utf8mb3_bin'),
               existing_nullable=True)

    # ### end Alembic commands ###
