"""utf8mb4 further support, change collation

Revision ID: 6cda7c6eaf51
Revises: 41c3e9dcdfce
Create Date: 2024-07-29 10:18:25.177414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cda7c6eaf51'
down_revision = '41c3e9dcdfce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=100),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=5000),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=5000),
               existing_nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               existing_nullable=True)
        batch_op.alter_column('sanitized_title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=150),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=150),
               existing_nullable=False)
        batch_op.alter_column('subtitle',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=150),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=150),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=150),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=150),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=25),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=25),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=25),
               existing_nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=150),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=150),
               existing_nullable=False)
        batch_op.alter_column('subtitle',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=150),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=150),
               existing_nullable=True)
        batch_op.alter_column('sanitized_title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=150),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=150),
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=5000),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=5000),
               existing_nullable=False)
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
