"""blog_id is string

Revision ID: 6d605126b6fa
Revises: bf70331a53a1
Create Date: 2024-05-03 09:13:51.898338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d605126b6fa'
down_revision = 'bf70331a53a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('blog_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb3_bin'),
               type_=sa.Text(length=100000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(length=100000),
               type_=mysql.MEDIUMTEXT(collation='utf8mb3_bin'),
               existing_nullable=False)
        batch_op.alter_column('blog_id',
               existing_type=sa.String(length=5),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
