"""init

Revision ID: 7590805c41e8
Revises: 
Create Date: 2024-03-09 13:27:05.929182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7590805c41e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('sanitized_title', sa.String(length=250), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(length=100000), nullable=False),
    sa.Column('comment_ids', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_ids'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sanitized_title'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('img_pos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_img_pos'), ['img_pos'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=10000),
               type_=sa.Text(length=10000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(length=10000),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=10000),
               existing_nullable=False)

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_img_pos'))

    op.drop_table('image')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))

    op.drop_table('post')
    # ### end Alembic commands ###
