"""rename blogpage title and subtitle to name and subname

Revision ID: 79665802aa08
Revises: 6cda7c6eaf51
Create Date: 2024-08-07 00:11:00.162998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79665802aa08'
down_revision = '6cda7c6eaf51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.alter_column(column_name='subtitle', new_column_name='subname', existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100))
        batch_op.alter_column(column_name='title', new_column_name='name', existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('subname')

    # ### end Alembic commands ###
