"""rename "edited" to "updated" for timstamp

Revision ID: 89cba79ed5d8
Revises: e0f3afbf94b8
Create Date: 2025-01-31 07:11:05.929434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89cba79ed5d8'
down_revision = 'e0f3afbf94b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.alter_column('is_all_posts',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=False)
        batch_op.alter_column('is_login_required',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=False)
        batch_op.alter_column('is_published',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=False)
        batch_op.alter_column('is_writeable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('NOW()'),
               existing_nullable=False)
        batch_op.alter_column('is_unread',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column(column_name='edited_timestamp', new_column_name='updated_timestamp', existing_type=sa.DateTime())
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('NOW()'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column(column_name='updated_timestamp', new_column_name='edited_timestamp', existing_type=sa.DateTime())
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('is_unread',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)

    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.alter_column('is_writeable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('is_published',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('is_login_required',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
        batch_op.alter_column('is_all_posts',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)

    # ### end Alembic commands ###
