"""apparently order is a sql keyword

Revision ID: 9881579760bc
Revises: 59fea7266543
Create Date: 2024-06-06 08:08:12.128890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9881579760bc'
down_revision = '59fea7266543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordering', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_blogpage_order')
        batch_op.create_index(batch_op.f('ix_blogpage_ordering'), ['ordering'], unique=False)
        batch_op.drop_column('order')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb3_bin'),
               type_=sa.Text(length=100000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(length=100000),
               type_=mysql.MEDIUMTEXT(collation='utf8mb3_bin'),
               existing_nullable=False)

    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_blogpage_ordering'))
        batch_op.create_index('ix_blogpage_order', ['order'], unique=False)
        batch_op.drop_column('ordering')

    # ### end Alembic commands ###
