"""test

Revision ID: a48f9d6f41da
Revises: 58d2d0f0322d
Create Date: 2024-07-29 09:51:01.518164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a48f9d6f41da'
down_revision = '58d2d0f0322d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.UnicodeText(length=100000),
               existing_nullable=True)
        batch_op.alter_column('sanitized_title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('sanitized_title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=150),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.UnicodeText(length=100000),
               type_=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)

    # ### end Alembic commands ###
