"""remove old blog_id column

Revision ID: b7183dac0f63
Revises: c8e053187a0b
Create Date: 2024-06-06 09:40:52.501836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7183dac0f63'
down_revision = 'c8e053187a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb3_bin'),
               type_=sa.Text(length=100000),
               existing_nullable=False)
        batch_op.drop_index('ix_post_blog_id')
        batch_op.drop_column('blog_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_id', mysql.VARCHAR(collation='utf8mb3_bin', length=5), nullable=False))
        batch_op.create_index('ix_post_blog_id', ['blog_id'], unique=False)
        batch_op.alter_column('content',
               existing_type=sa.Text(length=100000),
               type_=mysql.MEDIUMTEXT(collation='utf8mb3_bin'),
               existing_nullable=False)

    # ### end Alembic commands ###
