"""posts have edited timestamp

Revision ID: bbcbf00a858e
Revises: faaf531f88bb
Create Date: 2024-03-10 06:41:55.337852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbcbf00a858e'
down_revision = 'faaf531f88bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('content',
               existing_type=mysql.MEDIUMTEXT(charset='utf8mb3', collation='utf8mb3_bin'),
               type_=sa.Text(length=100000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(length=100000),
               type_=mysql.MEDIUMTEXT(charset='utf8mb3', collation='utf8mb3_bin'),
               existing_nullable=False)
        batch_op.drop_column('edited_timestamp')

    # ### end Alembic commands ###
