"""change unpublished to published

Revision ID: c1ac6b60fab0
Revises: dd81a3c83f5c
Create Date: 2024-09-29 22:56:56.726585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1ac6b60fab0'
down_revision = 'dd81a3c83f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.alter_column(column_name='unpublished', new_column_name='published', existing_type=mysql.TINYINT())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.alter_column(column_name='published', new_column_name='unpublished', existing_type=mysql.TINYINT())

    # ### end Alembic commands ###
