"""complete adding ordering

Revision ID: c8e053187a0b
Revises: 9881579760bc
Create Date: 2024-06-06 08:10:00.873068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8e053187a0b'
down_revision = '9881579760bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.alter_column('ordering',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_blogpage_ordering')
        batch_op.create_index(batch_op.f('ix_blogpage_ordering'), ['ordering'], unique=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb3_bin'),
               type_=sa.Text(length=100000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(length=100000),
               type_=mysql.MEDIUMTEXT(collation='utf8mb3_bin'),
               existing_nullable=False)

    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogpage_ordering'))
        batch_op.create_index('ix_blogpage_ordering', ['ordering'], unique=False)
        batch_op.alter_column('ordering',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
