"""make color not nullable

Revision ID: d4b2eff3dfb3
Revises: 2618b71f1f4a
Create Date: 2024-09-29 23:13:48.552607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4b2eff3dfb3'
down_revision = '2618b71f1f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               server_default="black")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpage', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               server_default=None)

    # ### end Alembic commands ###
