"""collation charset test 2

Revision ID: edd132b78832
Revises: 35a55c3553be
Create Date: 2024-07-29 09:54:40.114674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edd132b78832'
down_revision = '35a55c3553be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.UnicodeText(length=100000, collation='utf8mb4_bin'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.UnicodeText(length=100000, collation='utf8mb4_bin'),
               type_=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)

    # ### end Alembic commands ###
